
export const PRODUCTACTIONTYPES = {


    /**
     * GET PRODUCT LIST ACTION TYPES
     */

    PRODUCT_LIST_FETCH_START:"PRODUCT_LIST_FETCH_START",
    PRODUCT_LIST_FETCH_SUCCESS:"PRODUCT_LIST_FETCH_SUCCESS",
    PRODUCT_LIST_FETCH_FAILURE:"PRODUCT_LIST_FETCH_FAILURE",

     /**
     * GET PRODUCT DETAILS ACTION TYPES
     */

      PRODUCT_DETAILS_FETCH_START:"PRODUCT_DETAILS_FETCH_START",
      PRODUCT_DETAILS_FETCH_SUCCESS:"PRODUCT_DETAILS_FETCH_SUCCESS",
      PRODUCT_DETAILS_FETCH_FAILURE:"PRODUCT_DETAILS_FETCH_FAILURE",
  
  

    /**
     * CREATE PRODUCT TYPES
     */

    PRODUCT_CREATE_START:"PRODUCT_CREATE_START",
    PRODUCT_CREATE_SUCCESS:"PRODUCT_CREATE_SUCCESS",
    PRODUCT_CREATE_FAILURE:"PRODUCT_CREATE_FAILURE",


}





